# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Plugin coordinates
version=1.0.0
maven_group=com.example.moemusic.template

# Dependencies
plugin_api_version=2.2.0
# MoeMusic's no-api components should not be used in plugins. We reference it here *only* for setting version constraints.
moemusic_version=1.4.0
fabric_loader=0.19.5
forge_loader=1.18.2-40.3.12
# 3.0.13 is the last version that targets java 17
neoforged_loader=3.0.13

# Minecraft Mod Metadata (for Fabric, Forge, and NeoForge loaders)
mod_id=moemusic_example_template
mod_name=MoeMusic - Example Template Source
mod_description=Minimal standalone plugin and Minecraft mod template for MoeMusic.
mod_author=Example
mod_license=AGPL-3.0-or-later
fabric_entrypoint=com.example.moemusic.template.platform.FabricEntrypoint
